### ISSUE TITLE
problem with the transaction

### ISSUE THREAD

**Issue by beroin** [MonetaryUnit/MUE-Src#13]
Hello. April 21, I sent the coin, but they have not reached probably is a mistake, whether it is possible to solve it? Later I sent a little coins and they came immediately. 
details of the transaction:
first                                    second                              third
Status: 0 / not confirmed    | Status: 0 / not confirmed    | Status: 2385 confirmation
Date: 21/04/2015 6:35       | Date: 21.04.2015 14:44     | Date: 24.04.2015 03:45
Debit: -10000.00 MUE        | Debit: -1600.00 MUE          | Debit: -20.00 MUE
Commission: -0.0084 MUE | Commission: -0.0064 MUE | Commission: not
only the third transaction is successful
transaction id:
first: eecd8c1b87a206e59ef14e4830a2caef3a5a667337bd5544f77067a58f4918f3-000
second: 7c558174077826e1b6d9378ba20fcc131651f91115c18977e7bf71e05a4ca3ce-000
third: 577da13f5b112b4d09867f46650e6edee1984324cdd56506b450770ec6f405ee-000
in all cases was a recipient (bittrex): 77jNHEtEZMY8G8R2HW1WfDRCvVBADioHtb
My address (the sender): 74CQoLs8drc5ZNq8qeZV5zP2xpnJiEZLCt
Is it possible to return the coins from a failed transactions?
![060a6-clip-21kb](https://cloud.githubusercontent.com/assets/12100134/7322237/23baceb0-eaea-11e4-9127-de55f761d4c6.png)
![5b25b-clip-7kb](https://cloud.githubusercontent.com/assets/12100134/7322244/2e29f218-eaea-11e4-8f30-8eef0e4c7106.png)
![3fe95-clip-7kb](https://cloud.githubusercontent.com/assets/12100134/7322245/3011f08a-eaea-11e4-8353-0d0430bbe597.png)
![d56fd-clip-7kb](https://cloud.githubusercontent.com/assets/12100134/7322272/57b863a8-eaea-11e4-944c-b7c9c143554e.png)

**Comment by upgradeadvice** [comment]
First, make a backup of your wallet, then close the Qt client and relaunch with:
```
monetaryunit-qt -zapwallettxes
```
This should bring back your non-relayed txs/coins

I believe this issue is due to your wallet containing a LOT of small transactions, and the client could be miscalculating the fee. I will look into this further. Meanwhile, try the following before sending again.
```
monetaryunit-qt -paytxfee=0.009
```

**Comment by beroin** [comment]
Thank you very much! -zapwallettxes helped.

**Comment by beroin** [comment]
and yes indeed I have many mining transactions

**Comment by beroin** [comment]
but fails to send coins

**Comment by beroin** [comment]
confirmed only small amounts of coins

**Comment by upgradeadvice** [comment]
Try increasing the txfee manually. I am working on a fix.

**Comment by beroin** [comment]
problem occurs less frequently, but still there.
