### ISSUE TITLE
windows wallet

### ISSUE THREAD

**Issue by cinnamoncoin** [MonetaryUnit/MUE-Src#2]
It was brought to my attention there was some difficulty in a proper build of this wallet, it appears to build ok for me.  Loads on win 8, 8.1, 7 , suggest testing however as my time is limited. 
https://github.com/cinnamoncoin/MUE-Src/releases

**Comment by upgradeadvice** [comment]
Yours is dynamically linked, and the previous releases are all static.

Here is my latest static build.
https://github.com/MonetaryUnit/MUE-Src/releases/tag/1.0.0.0-020415
