### ISSUE TITLE
error code versus actual tx fee

### ISSUE THREAD

**Issue by drakoin** [MonetaryUnit/MUE-Src#4]
error: {"code":-4,"message":"Error: This transaction requires a transaction fee of at 
    least 0.0000001 because of its amount, complexity, or use of recently received funds!"}

BUT the actual tx fee seems to be:

0.0001

**Comment by upgradeadvice** [comment]
Which version?

**Comment by upgradeadvice** [comment]
Closed: no reply
Try the latest version and let us know if the issue persists.
