### ISSUE TITLE
Application crashes on launch

### ISSUE THREAD

**Issue by cmakaloclifford** [MonetaryUnit/MUE-Src#9]
Problems when launching application. Instantly crashes.

Error details:

Process:               MonetaryUnit-Qt [14744]
Path:                  /Applications/MonetaryUnit-Qt.app/Contents/MacOS/MonetaryUnit-Qt
Identifier:            org.monetaryunitfoundation.MonetaryUnit-Qt
Version:               1.0.0 (1.0.0)
Code Type:             X86-64 (Native)
Parent Process:        ??? [1]
Responsible:           MonetaryUnit-Qt [14744]
User ID:               501

Date/Time:             2015-03-24 11:38:28.959 +0100
OS Version:            Mac OS X 10.10.2 (14C1514)
Report Version:        11
Anonymous UUID:        C28A0FC8-DDCC-2D27-9E9E-81B2D957B115

Sleep/Wake UUID:       C1957A55-83FF-4A77-B0C0-927873611D70

Time Awake Since Boot: 110000 seconds
Time Since Wake:       13000 seconds

Crashed Thread:        0  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000

Application Specific Information:
abort() called

Thread 0 Crashed:: Dispatch queue: com.apple.main-thread
0   libsystem_kernel.dylib        	0x00007fff9be45286 __pthread_kill + 10
1   libsystem_c.dylib             	0x00007fff9b5b9b53 abort + 129
2   org.monetaryunitfoundation.MonetaryUnit-Qt	0x0000000106978dc9 0x106531000 + 4488649
3   org.monetaryunitfoundation.MonetaryUnit-Qt	0x0000000106979311 0x106531000 + 4490001
4   org.monetaryunitfoundation.MonetaryUnit-Qt	0x0000000106e492dd 0x106531000 + 9536221
5   org.monetaryunitfoundation.MonetaryUnit-Qt	0x0000000106e492fb 0x106531000 + 9536251
6   org.monetaryunitfoundation.MonetaryUnit-Qt	0x0000000106ab7808 0x106531000 + 5793800
7   org.monetaryunitfoundation.MonetaryUnit-Qt	0x0000000106ab7777 0x106531000 + 5793655
8   org.monetaryunitfoundation.MonetaryUnit-Qt	0x0000000106e4734e 0x106531000 + 9528142
9   org.monetaryunitfoundation.MonetaryUnit-Qt	0x0000000106be99ee 0x106531000 + 7047662
10  org.monetaryunitfoundation.MonetaryUnit-Qt	0x0000000106534a28 0x106531000 + 14888
11  org.monetaryunitfoundation.MonetaryUnit-Qt	0x00000001065327f4 0x106531000 + 6132

Thread 0 crashed with X86 Thread State (64-bit):
  rax: 0x0000000000000000  rbx: 0x0000000000000006  rcx: 0x00007fff596ce478  rdx: 0x0000000000000000
  rdi: 0x000000000000130f  rsi: 0x0000000000000006  rbp: 0x00007fff596ce4a0  rsp: 0x00007fff596ce478
   r8: 0x000000000000003d   r9: 0x00007fc63b400000  r10: 0x0000000008000000  r11: 0x0000000000000206
  r12: 0x00007fff596ce768  r13: 0x00007fff596ceacc  r14: 0x00007fff7e9d9300  r15: 0x00007fff596ceb68
  rip: 0x00007fff9be45286  rfl: 0x0000000000000206  cr2: 0x00007fff7ec9ffd8
  
Logical CPU:     0
Error Code:      0x02000148
Trap Number:     133

**Comment by upgradeadvice** [comment]
Unfortunately, the mac build is completely untested. Would you be able to post a sanitized debug log to a pastebin?

**Comment by upgradeadvice** [comment]
closed: no reply

try the latest version and let us know if the issue persists
